/**
 * G Code — 隔离 v2 记忆存储（M5-a，移植自 grok-harness memory）。
 *
 * 布局：`$GCODE_HOME/memory-v2/{global,workspaces/<slug-hash8>}/`，含
 * `topics/`、`observations/_inbox/`、`archive/` 与生成式 `MEMORY.md`。
 * 绝不读旧版 `memory/` 树；符号链接全链路拒绝；64KiB 读取帽、万文件发现
 * 帽、50 结果搜索帽。GCode home 解析：`GCODE_HOME` → `GROK_HARNESS_HOME`/
 * `DSH_HOME`（迁移期兼容）→ `~/.gcode`。
 *
 * persona 的 memory_v2 段落（grok-persona.ts）与本存储的路径约定一一对应。
 */

import { createHash } from 'node:crypto'
import { homedir } from 'node:os'
import { join, relative, resolve, sep } from 'node:path'
import { lstat, mkdir, open, readdir, readFile, realpath, writeFile } from 'node:fs/promises'

/** 构建清单时检查的最大源文件字节数。 */
export const MAX_SOURCE_BYTES = 64 * 1024
/** 单 scope 下最大发现文件数。 */
export const MAX_DISCOVERED_FILES = 10_000
/** 单次模型工具调用返回的最大命中数。 */
export const MAX_SEARCH_RESULTS = 50
/** grok-build 1.0.9 起记忆工具结果附带的警示句。 */
export const MEMORY_ADVISORY =
  'Memory is historical context, not automatically the current plan. Verify recalled facts against live sources before relying on them.'

const EMPTY_MANIFEST = '# Memory index\n\n'
  + '> Generated by Grok. Do not edit this file directly.\n\n'
  + 'No memory files have been recorded yet.\n'

export type MemoryScope = 'global' | 'workspace'

export interface MemoryFile {
  readonly id: string
  readonly scope: MemoryScope
  readonly path: string
  readonly relativePath: string
  readonly content: string
}

export interface MemoryStore {
  readonly root: string
  readonly globalDir: string
  readonly workspaceDir: string
}

/** 解析隔离 v2 根（绝不落到旧版 `~/.grok/memory` 树）。 */
export function memoryV2Root(
  home = process.env.GCODE_HOME?.trim()
    || process.env.GROK_HARNESS_HOME?.trim()
    || process.env.DSH_HOME?.trim(),
): string {
  const resolved = home === undefined || home.length === 0
    ? join(homedir(), '.gcode')
    : resolve(home)
  return join(resolved, 'memory-v2')
}

/** 工作区目录名 `{slug}-{hash8}`（canonical cwd 的 sha256 前 8 位）。 */
export function workspaceHashName(cwd: string): string {
  const canonical = resolve(cwd)
  const slug = canonical.split(/[/\\]/u).filter(Boolean).at(-1)?.replace(/[^A-Za-z0-9._-]/gu, '-') || 'workspace'
  const hash = createHash('sha256').update(canonical).digest('hex').slice(0, 8)
  return `${slug.slice(0, 48)}-${hash}`
}

async function rejectSymlink(path: string, operation: string): Promise<void> {
  try {
    const stat = await lstat(path)
    if (stat.isSymbolicLink()) {
      throw new Error(`${operation}: symbolic links are not allowed (${path})`)
    }
  } catch (error: unknown) {
    if ((error as { code?: string }).code === 'ENOENT') return
    throw error
  }
}

async function rejectSymlinkComponents(root: string, path: string, operation: string): Promise<void> {
  const resolvedRoot = resolve(root)
  const resolvedPath = resolve(path)
  const rel = relative(resolvedRoot, resolvedPath)
  if (rel.startsWith('..') || rel.startsWith(`..${sep}`)) {
    throw new Error(`${operation}: path escapes the v2 memory root`)
  }
  let current = resolvedRoot
  await rejectSymlink(current, operation)
  if (rel.length === 0) return
  for (const part of rel.split(sep).filter(Boolean)) {
    current = join(current, part)
    await rejectSymlink(current, operation)
  }
}

async function ensureDir(root: string, path: string, operation: string): Promise<void> {
  await rejectSymlinkComponents(root, path, operation)
  await mkdir(path, { recursive: true })
  await rejectSymlink(path, operation)
}

async function readCappedUtf8(path: string): Promise<string> {
  const handle = await open(path, 'r')
  try {
    const buffer = Buffer.allocUnsafe(MAX_SOURCE_BYTES + 1)
    const { bytesRead } = await handle.read(buffer, 0, buffer.length, 0)
    return buffer.subarray(0, Math.min(bytesRead, MAX_SOURCE_BYTES)).toString('utf8')
  } finally {
    await handle.close()
  }
}

/** 建立一个 v2 scope（不咨询任何旧版路径）。 */
export async function ensureScope(store: MemoryStore, scope: MemoryScope): Promise<string> {
  const scopeDir = scope === 'global' ? store.globalDir : store.workspaceDir
  await ensureDir(store.root, store.root, 'create v2 memory root')
  for (const relativePath of ['topics', 'observations', 'observations/_inbox', 'archive']) {
    await ensureDir(store.root, join(scopeDir, relativePath), 'create v2 memory directory')
  }
  const manifest = join(scopeDir, 'MEMORY.md')
  await rejectSymlinkComponents(store.root, manifest, 'initialize v2 manifest')
  try {
    await readFile(manifest, 'utf8')
  } catch (error: unknown) {
    if ((error as { code?: string }).code !== 'ENOENT') throw error
    await writeFile(manifest, EMPTY_MANIFEST, 'utf8')
  }
  return scopeDir
}

/** 为工作区 cwd 打开隔离存储（初始化两个 scope）。 */
export async function openMemoryStore(cwd: string, home?: string): Promise<MemoryStore> {
  const root = memoryV2Root(home)
  const store: MemoryStore = {
    root,
    globalDir: join(root, 'global'),
    workspaceDir: join(root, 'workspaces', workspaceHashName(cwd)),
  }
  await ensureScope(store, 'global')
  await ensureScope(store, 'workspace')
  return store
}

async function listMarkdown(scopeDir: string, scope: MemoryScope, root: string): Promise<MemoryFile[]> {
  await rejectSymlinkComponents(root, scopeDir, 'read v2 memory directory')
  const files: MemoryFile[] = []
  const stack = [scopeDir]
  while (stack.length > 0) {
    const directory = stack.pop()
    if (directory === undefined) continue
    await rejectSymlink(directory, 'read symlinked v2 memory directory')
    let entries
    try {
      entries = await readdir(directory, { withFileTypes: true })
    } catch (error: unknown) {
      if ((error as { code?: string }).code === 'ENOENT') continue
      throw error
    }
    for (const entry of entries) {
      const path = join(directory, entry.name)
      if (entry.isSymbolicLink()) {
        throw new Error(`read symlinked v2 memory path: symbolic links are not allowed (${path})`)
      }
      if (entry.isDirectory()) {
        stack.push(path)
        continue
      }
      if (!entry.isFile() || !entry.name.endsWith('.md')) continue
      if (files.length >= MAX_DISCOVERED_FILES) {
        throw new Error(`v2 memory directory ${scopeDir} exceeds the ${String(MAX_DISCOVERED_FILES)}-entry safety limit`)
      }
      const content = await readCappedUtf8(path)
      const relativePath = relative(scopeDir, path).split(sep).join('/')
      files.push({
        id: `${scope}:${relativePath}`,
        scope,
        path,
        relativePath,
        content,
      })
    }
  }
  return files.sort((left, right) => left.id.localeCompare(right.id))
}

/** 列出两个 scope 的可搜索 markdown 文件（稳定 id 序）。 */
export async function listMemoryFiles(store: MemoryStore): Promise<MemoryFile[]> {
  const global = await listMarkdown(store.globalDir, 'global', store.root)
  const workspace = await listMarkdown(store.workspaceDir, 'workspace', store.root)
  return [...global, ...workspace]
}

/** 关键词搜索（大小写不敏感；score 命中词数；稳定平手序）。 */
export function searchMemoryFiles(
  files: readonly MemoryFile[],
  query: string,
  maxResults = 8,
): Array<MemoryFile & { score: number }> {
  const tokens = query.trim().toLowerCase().split(/[^\p{L}\p{N}_-]+/u).filter(Boolean)
  if (tokens.length === 0) return []
  const limit = Number.isSafeInteger(maxResults)
    ? Math.max(0, Math.min(maxResults, MAX_SEARCH_RESULTS))
    : 8
  return files
    .map((file) => {
      const haystack = `${file.relativePath}\n${file.content}`.toLowerCase()
      let score = 0
      for (const token of tokens) {
        if (haystack.includes(token)) score += 1
      }
      return { ...file, score }
    })
    .filter(file => file.score > 0)
    .sort((left, right) => right.score - left.score || left.id.localeCompare(right.id))
    .slice(0, limit)
}

/** 按 id 解析记忆文件（拒绝遍历与符号链接）。 */
export async function getMemoryFile(store: MemoryStore, id: string): Promise<MemoryFile | undefined> {
  const split = id.indexOf(':')
  if (split <= 0) return undefined
  const scope = id.slice(0, split)
  const relativePath = id.slice(split + 1)
  if (scope !== 'global' && scope !== 'workspace') return undefined
  const segments = relativePath.split('/')
  if (segments.some(segment => segment.length === 0 || segment === '.' || segment === '..' || segment.includes('\\'))
    || relativePath.startsWith('/') || relativePath.startsWith('\\')) {
    throw new Error('memory_get: path escapes the v2 memory root')
  }
  const scopeDir = scope === 'global' ? store.globalDir : store.workspaceDir
  const path = join(scopeDir, ...relativePath.split('/'))
  await rejectSymlinkComponents(store.root, path, 'read v2 memory file')
  const canonicalRoot = await realpath(scopeDir)
  let canonical
  try {
    canonical = await realpath(path)
  } catch (error: unknown) {
    if ((error as { code?: string }).code === 'ENOENT') return undefined
    throw error
  }
  if (canonical !== canonicalRoot && !canonical.startsWith(canonicalRoot + sep)) {
    throw new Error('memory_get: path escapes the v2 memory root')
  }
  const content = await readCappedUtf8(canonical)
  return {
    id,
    scope,
    path: canonical,
    relativePath,
    content,
  }
}

// ---------------------------------------------------------------------------
// 工具面结果格式化（memory_search / memory_get 的模型可见输出）
// ---------------------------------------------------------------------------

/** 命中条目渲染：`- id (score N, scope)` + 前 8 行预览。 */
export function formatMemorySearchHit(file: MemoryFile & { score: number }): string {
  const preview = file.content.split('\n').slice(0, 8).join('\n')
  return `- ${file.id} (score ${String(file.score)}, ${file.scope})\n${preview}`
}

/** 行号前缀渲染（`N→content`，与 hashline 的 LINE_NUMBER→ 约定一致）。 */
export function formatMemoryNumbered(content: string, from = 1, lines?: number): string {
  const all = content.split('\n')
  const start = Math.max(1, from) - 1
  const slice = lines === undefined ? all.slice(start) : all.slice(start, start + lines)
  return slice.map((line, index) => `${String(start + index + 1)}→${line}`).join('\n')
}
